feat: Full TOML path tracking in FromToml for errors
Use a stack based link-list to track for path of Toml item's during
FromToml conversion, so that errors and reconstruct the full path.

This allows for errors like the following:

error: unexpected key `bogus` at component.servers[1].config
   ┌─ nested_unexpected_key:11:1
   │
11 │ bogus = true
   │ ^^^^^ unexpected key

Note the `component.servers[1].config` in error message providing the
context of where the issue occoured semantically beyond just the span
information.

Especially with larger tables, this makes issues easier to diagnose common
cases.

Further, the fully path realized in error can be displayed even without
the original source, which means we ensure decent enough errors developers
see during initial integration.

One of the main motivating factors for implementing this feature was
cargo's current implementation which attempts to provide these paths
in an adhoc and inconsistent manner.

Still some edge-cases to handle and trade offs in the implementation,
but overall I think it's an improvement. The main trade off's here is
now the Error type has lifetime dependent on the Arena.

The added complexity introduced some slight regressions across the board:
- 1-10% check time regression
- 1-10% build time regression
- 1-5% Binary size regression
- 1-3% Performance regression

Given that we still ahead of all competing libraries across every benchmark,
with few exceptions while now providing improved error messages, I've deemed
it worth it.